logging.level.org.zalando.logbook: TRACE
server:
  port: 8080
spring:
  sql.init.mode: always
  application.name: shareit
  main.banner-mode: OFF
  jpa:
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC
  datasource:
    username: "dbuser"
    password: "12345"
    url: "jdbc:postgresql://localhost:5432/shareit"
    driver-class-name: "org.postgresql.Driver"

